#!/usr/bin/env bash
# Write a Bash script that will display information about subdomains

# DNS CONFIGURATION VALUES
# www       => 34.207.61.142
# lb-01     => 34.207.61.142
# web-01    => 54.90.10.137
# web-02    => 54.144.157.3

digFunction () {
    domain_name="$1"
    subdomain_name="$2"

    dig "$subdomain_name"."$domain_name" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v subdomain="$subdomain_name" 'BEGIN { FS = " " }; { print "The subdomain " subdomain " is a " $4 " record and points to " $5 }'
}

all_subdomain_list=( "www" "lb-01" "web-01" "web-02" )

if [ $# -eq 2 ];
then
    domain_name="$1"
    subdomain_name="$2"

    digFunction "$domain_name" "$subdomain_name"

elif [ $# -eq 1 ];
then
    domain_name="$1"

    for value in "${all_subdomain_list[@]}"
    do
        digFunction "$domain_name" "$value"
    done
fi
