#!/usr/bin/env bash
# Install nginx on the web server to listen on port 80
# Returns a page with "Hello World" on it

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

sudo service nginx start
