#!/usr/bin/env bash
# Configure web-02 to be identical to web-01
# Include a custom header for each server

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow "Nginx HTTP"

mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

SERVER_CONFIGURATION=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /error404.html;
    location = /error404.html {
        internal;
    }

    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}"

echo "Ceci n'est pas une page" > /var/www/html/error404.html

echo -e "$SERVER_CONFIGURATION" > /etc/nginx/sites-enabled/default
sudo service nginx restart