#!/usr/bin/env bash
# Same as task 0 but status of nginx should be "* nginx is not running"
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" > /run/nginx.pid
