#!/usr/bin/env bash
# Same as task 1
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sed -i 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sudo --user=nginx service nginx restart
